- id: diagnostics_unavailable_entities
  alias: Diagnostics - Notify unavailable entities
  description: "주기적으로 'unavailable'/'unknown' 엔티티 목록을 알림으로 표시합니다."
  trigger:
    - platform: homeassistant
      event: start
    - platform: time_pattern
      minutes: "/15"
  condition: []
  action:
    - variables:
        problem_list: >-
          {{ states | selectattr('state', 'in', ['unavailable','unknown'])
                     | map(attribute='entity_id') | list }}
    - choose:
        - conditions: "{{ problem_list | length > 0 }}"
          sequence:
            - service: persistent_notification.create
              data:
                title: >-
                  Unavailable/Unknown entities ({{ problem_list | length }})
                message: >-
                  {{ problem_list | join('\n') }}
                notification_id: unavailable_entities
        - conditions: "{{ problem_list | length == 0 }}"
          sequence:
            - service: persistent_notification.dismiss
              data:
                notification_id: unavailable_entities
  mode: restart

- id: enhanced_unavailable_monitoring
  alias: Enhanced Unavailable Entities Monitoring
  description: "향상된 unavailable 엔티티 모니터링 및 분류 시스템"
  trigger:
    - platform: homeassistant
      event: start
    - platform: time_pattern
      minutes: "/10"
    - platform: state
      entity_id: sensor.unavailable_entities_count
  condition: []
  action:
    - variables:
        all_unavailable: >-
          {{ states | selectattr('state', 'in', ['unavailable','unknown'])
                     | map(attribute='entity_id') | list }}
        classifications:
          thinq_fridge: >-
            {{ all_unavailable | select('match', 'sensor.jubang_gimcinaengjanggo.*temperature') | list }}
          thinq_dishwasher: >-
            {{ all_unavailable | select('match', 'sensor.jubang_siggiseceoggi.*') | list }}
          apple_batteries: >-
            {{ all_unavailable | select('match', 'sensor..*battery') | list }}
          ble_sensors: >-
            {{ all_unavailable | select('match', '.*ble.*') | list }}
          xbox_entities: >-
            {{ all_unavailable | select('match', '.*xbox.*') | list }}
          network_sensors: >-
            {{ all_unavailable | select('match', 'sensor..*router.*|sensor.fast_com.*') | list }}
          other_sensors: >-
            {{ all_unavailable | reject('match', 'sensor.jubang_.*|sensor..*battery|.*ble.*|.*xbox.*|sensor..*router.*|sensor.fast_com.*') | list }}
    - service: system_log.write
      data:
        message: >
          🔍 Unavailable Entities 분석 결과:
          📊 총계: {{ all_unavailable | length }}개
          
          📂 카테고리별 분석:
          🧊 김치냉장고 온도: {{ classifications.thinq_fridge | length }}개
          🍽️ 식기세척기: {{ classifications.thinq_dishwasher | length }}개  
          🔋 Apple 배터리: {{ classifications.apple_batteries | length }}개
          📡 BLE 센서: {{ classifications.ble_sensors | length }}개
          🎮 Xbox: {{ classifications.xbox_entities | length }}개
          🌐 네트워크: {{ classifications.network_sensors | length }}개
          ❓ 기타: {{ classifications.other_sensors | length }}개
        level: info
    - choose:
        - conditions: "{{ classifications.thinq_fridge | length > 0 }}"
          sequence:
            - service: persistent_notification.create
              data:
                title: "⚠️ 김치냉장고 온도 센서 문제"
                message: >
                  **문제 센서들:**
                  {{ classifications.thinq_fridge | join('\n') }}
                  
                  **영향도 분석:**
                  - 평균 온도 센서: {{ 'PARTIAL' if classifications.thinq_fridge | length < 4 else 'DOWN' }}
                  - 사용 가능한 센서: {{ states.sensor.kimchi_fridge_avg_temperature.attributes.available_sensors | default('unknown') }}
                  
                  **권장 조치:**
                  1. 스크립트 실행: `thinq_integration_reload`
                  2. LG ThinQ 앱에서 기기 상태 확인
                  3. 네트워크 연결 상태 점검
                notification_id: thinq_fridge_alert
    - choose:
        - conditions: "{{ classifications.apple_batteries | length > 0 }}"
          sequence:
            - service: persistent_notification.create
              data:
                title: "🍎 Apple 기기 배터리 센서 문제"
                message: >
                  **문제 센서들:**
                  {{ classifications.apple_batteries | join('\n') }}
                  
                  **권장 조치:**
                  1. iCloud3 통합 상태 확인
                  2. 각 기기에서 Home Assistant Companion 앱 확인
                  3. "나의 찾기" 활성화 여부 확인
                  4. 스크립트 실행: `apple_devices_battery_check`
                notification_id: apple_battery_alert
    - choose:
        - conditions: "{{ classifications.ble_sensors | length > 0 }}"
          sequence:
            - service: persistent_notification.create
              data:
                title: "📡 BLE 센서 연결 문제"
                message: >
                  **문제 센서들:**
                  {{ classifications.ble_sensors | join('\n') }}
                  
                  **권장 조치:**
                  1. 스크립트 실행: `bluetooth_adapter_reset`
                  2. BLE 장치들 물리적 재부팅
                  3. 블루투스 어댑터 전원 관리 설정 확인
                notification_id: ble_sensor_alert
    - service: persistent_notification.create
      data:
        title: "📊 시스템 상태 요약"
        message: >
          **전체 시스템 상태** ({{ now().strftime('%Y-%m-%d %H:%M') }})
          
          🟢 **정상 작동 중:**
          - 시스템 센서: {{ states.sensor | selectattr('entity_id', 'match', 'sensor.(processor_use|memory_use_percent|disk_use_percent)') | selectattr('state', 'ne', 'unavailable') | list | length }}/3
          - 전력 센서: {{ states.sensor | selectattr('entity_id', 'match', '.*power') | selectattr('state', 'ne', 'unavailable') | list | length }}개
          - 온습도 센서: {{ states.sensor | selectattr('entity_id', 'match', '.*temperature|.*humidity') | selectattr('state', 'ne', 'unavailable') | list | length }}개
          
          🔴 **문제 발생:**
          - 총 unavailable: {{ all_unavailable | length }}개
          - 주요 문제: 
          {% if classifications.thinq_fridge | length > 0 %}  김치냉장고 ({{ classifications.thinq_fridge | length }}) {% endif %}
          {% if classifications.apple_batteries | length > 0 %}  Apple배터리 ({{ classifications.apple_batteries | length }}) {% endif %}
          {% if classifications.ble_sensors | length > 0 %}  BLE센서 ({{ classifications.ble_sensors | length }}) {% endif %}
          
          **복구 스크립트:** 설정 > 스크립트에서 실행 가능
        notification_id: system_status_summary
  mode: single
