# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include_dir_merge_list scenes
sensor: !include sensors.yaml
template: !include templates.yaml
influxdb: !include influxdb.yaml

# Reverse Proxy 설정
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24 # Supervisor 애드온 네트워크
    - 172.30.0.0/16 # NPM

# 재연결 및 타임아웃 설정
recorder:
  commit_interval: 5
  purge_keep_days: 7

# ===========================
# Lovelace 설정
# ===========================
# YAML 편집 모드 해제 (UI 편집 모드 사용)
lovelace:
  mode: storage
  resources:
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
  dashboards:
    ui-minimalist:
      mode: yaml
      filename: ui_lovelace_minimalist/dashboard/ui-lovelace.yaml
      title: UI Lovelace Minimalist
      icon: mdi:flower
      show_in_sidebar: true

