# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include_dir_merge_list automations
script: !include_dir_merge_named scripts
scene: !include_dir_merge_list scenes

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
    - 172.30.0.0/16

# ===========================
# 추가 센서 통합
# ===========================

# 시스템 모니터링
sensor:
  # (사용자 요청) systemmonitor 센서 제거

  # 시간 및 날짜
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'

  # (season/moon는 센서 플랫폼이 아닌 통합형식이므로 아래에 최상위 키로 선언)

# Sun integration (일출/일몰) - 제거 요청 없음, 유지
sun:

# (사용자 요청) season/moon 통합 제거

# 템플릿 센서 (사용자 정의 계산)
template:
  - sensor:
      # 총 전력 소비량
      - name: "total_power_consumption"
        unique_id: "total_power_consumption"
        unit_of_measurement: "W"
        state: >
          {% set ac = states('sensor.seutaendeuhyeong_eeokeon_power') | float(0) %}
          {% set kitchen = states('sensor.zigbee_dimmer_power') | float(0) %}
          {% set desktop = states('sensor.deseukeutab_jeonweon_power') | float(0) %}
          {{ (ac + kitchen + desktop) | round(2) }}
        icon: mdi:lightning-bolt

      # 평균 김치냉장고 온도
      - name: "kimchi_fridge_avg_temperature"
        unique_id: "kimchi_fridge_avg_temperature"
        unit_of_measurement: "°C"
        state: >
          {% set left = states('sensor.jubang_gimcinaengjanggo_left_temperature') | float(0) %}
          {% set middle = states('sensor.jubang_gimcinaengjanggo_middle_temperature') | float(0) %}
          {% set right = states('sensor.jubang_gimcinaengjanggo_right_temperature') | float(0) %}
          {% set bottom = states('sensor.jubang_gimcinaengjanggo_bottom_temperature') | float(0) %}
          {{ ((left + middle + right + bottom) / 4) | round(1) }}
        icon: mdi:thermometer

      # 평균 배터리 수준
      - name: "average_device_battery"
        unique_id: "average_device_battery"
        unit_of_measurement: "%"
        state: >
          {% set watch = states('sensor.gimuhyeonyi_apple_watch_battery') | float(0) %}
          {% set macbook = states('sensor.gimuhyeonyi_macbook_pro_battery') | float(0) %}
          {% set ipad = states('sensor.uhyeonyi_ipad_pro_battery') | float(0) %}
          {% set iphone = states('sensor.uhyeonyi_iphone_xs_battery') | float(0) %}
          {{ ((watch + macbook + ipad + iphone) / 4) | round(0) }}
        icon: mdi:battery

  - binary_sensor:
      # 저배터리 알림
      - name: "low_battery_devices"
        unique_id: "low_battery_devices"
        state: >
          {% set devices = [
            states('sensor.gimuhyeonyi_apple_watch_battery') | float(100),
            states('sensor.gimuhyeonyi_macbook_pro_battery') | float(100),
            states('sensor.uhyeonyi_ipad_pro_battery') | float(100),
            states('sensor.uhyeonyi_iphone_xs_battery') | float(100)
          ] %}
          {{ devices | select('<', 20) | list | length > 0 }}
        icon: mdi:battery-alert

      # 집에 사람 있음
      - name: "someone_home"
        unique_id: "someone_home"
        state: >
          {{ is_state('binary_sensor.iphone_presence', 'on') }}
        icon: mdi:home-account

# 근무일 센서는 UI를 통해 통합으로 설정
# Settings > Devices & Services > Add Integration > Workday

# ===========================
# 시스템 최적화 설정
# ===========================

# 로그 레벨 조정 (문제 있는 통합 로그 최소화)
logger:
  default: info
  logs:
    # Xbox 통합 로그 최소화 (네트워크 타임아웃 문제)
    homeassistant.components.xbox: error
    homeassistant.components.xbox.coordinator: error
    # 라즈베리파이 전력 경고 최소화
    homeassistant.components.rpi_power: error

# 시스템 리소스 최적화
system_health:

# ===========================
# InfluxDB 설정 (확장)
# ===========================
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state
  ssl: false
  verify_ssl: false
  precision: s

  # === 확장된 포함 설정 ===
  include:
    domains:
      - sensor
      - binary_sensor
      - climate
      - light
      - switch
      - weather        # 날씨 정보 포함
      - sun           # 일출/일몰 정보
      - person        # 사람 추적 (있을 경우)
    entities:
      # 기존 엔티티들 유지
      - climate.seutaendeuhyeong_eeokeon
      - sensor.seutaendeuhyeong_eeokeon_humidity
      - sensor.seutaendeuhyeong_eeokeon_temperature
      - sensor.seutaendeuhyeong_eeokeon_power
      - sensor.seutaendeuhyeong_eeokeon_power_energy
      - sensor.seutaendeuhyeong_eeokeon_energy
      - sensor.seutaendeuhyeong_eeokeon_energy_difference
      - sensor.seutaendeuhyeong_eeokeon_volume
      
      - light.zigbee_dimmer
      - light.smart_bulb
      - light.deseukeutab_jeonweon
      - sensor.zigbee_dimmer_power
      - sensor.zigbee_dimmer_energy
      - sensor.deseukeutab_jeonweon_power
      - sensor.deseukeutab_jeonweon_energy
      
      - sensor.192_168_1_1_devices_connected
      - sensor.fast_com_download
      - sensor.paul_router_download_speed
      - sensor.paul_router_upload_speed
      
      # 주방 가전
      - binary_sensor.jubang_siggiseceoggi_machine_clean_reminder
      - binary_sensor.jubang_siggiseceoggi_rinse_refill_needed
      - binary_sensor.jubang_siggiseceoggi_door
      - binary_sensor.jubang_siggiseceoggi_chime_sound
      - sensor.jubang_siggiseceoggi_remaining_time
      - sensor.jubang_siggiseceoggi_total_time
      - sensor.jubang_siggiseceoggi_softening_level
      - sensor.jubang_siggiseceoggi_delayed_start
      - sensor.jubang_siggiseceoggi_rinse_aid_dispenser_level
      
      - sensor.jubang_gimcinaengjanggo_bottom_temperature
      - sensor.jubang_gimcinaengjanggo_left_temperature
      - sensor.jubang_gimcinaengjanggo_middle_temperature
      - sensor.jubang_gimcinaengjanggo_right_temperature
      
      # 헬스 & BLE
      - sensor.ble_heart_rate_e0e33e6221b5
      - sensor.ble_steps_e0e33e6221b5
      - sensor.smart_series_7000_6f50
      - sensor.smart_series_7000_6f50_duration
      - sensor.smart_series_7000_6f50_pressure
      - binary_sensor.ble_toothbrush_f45eab216f50
      
      # 배터리
      - sensor.gimuhyeonyi_apple_watch_battery
      - sensor.gimuhyeonyi_macbook_pro_battery
      - sensor.uhyeonyi_ipad_pro_battery
      - sensor.uhyeonyi_iphone_xs_battery
      
      # 존재감지
      - binary_sensor.iphone_presence
      - binary_sensor.workday_sensor
      
      # 새로 추가된 시스템 센서들
      - sensor.disk_use_percent
      - sensor.memory_use_percent
      - sensor.processor_use
      - sensor.load_1m
      - sensor.load_5m
      - sensor.network_in_eth0
      - sensor.network_out_eth0
      - sensor.last_boot
      - sensor.time
      - sensor.date
      # season/moon 제거에 따른 제외
      - sun.sun
      
      # 템플릿 센서들
      - sensor.total_power_consumption
      - sensor.kimchi_fridge_avg_temperature
      - sensor.average_device_battery
      - binary_sensor.low_battery_devices
      - binary_sensor.someone_home

    entity_globs:
      # 기존 패턴들 유지
      - sensor.*_battery
      - sensor.*temperature*
      - sensor.*humidity*
      - sensor.*power*
      - sensor.*energy*
      - sensor.*voltage*
      - sensor.*current*
      - sensor.*co2*
      - sensor.*pm2_5*
      - sensor.*pm10*
      - sensor.*illuminance*
      - sensor.*lux*
      - sensor.*speed*        # 네트워크 속도 등
      - sensor.*_use*         # CPU, 메모리 사용률 등
      - sensor.*_load*        # 시스템 로드
      - binary_sensor.*motion*
      - binary_sensor.*occupancy*
      - binary_sensor.*presence*
      - binary_sensor.*door*
      - binary_sensor.*window*

  # === 제외 설정 (최소화) ===
  exclude:
    domains:
      - media_player           # 일단 유지 (선택적으로 포함 가능)
      - calendar              # 캘린더는 텍스트 위주라 제외
      - persistent_notification
      - automation            # 자동화 상태는 제외
      - script               # 스크립트 상태는 제외
    entity_globs:
      # Xbox 통합 제외 (네트워크 타임아웃 문제)
      - sensor.xbox_*
      - binary_sensor.xbox_*
      # 진단/링크 품질 관련
      - sensor.*_firmware*
      - sensor.*_availability
      - sensor.*_linkquality
      - sensor.*_lqi
      - sensor.*_last_seen
    entities:
      # 불필요한 텍스트/진단 센서들만 제외
      - sensor.cpu_speed
      - sensor.local_ip
      - sensor.uptime         # 시스템 가동시간은 last_boot으로 대체
      - sensor.icloud3_alerts
      - sensor.icloud3_event_log
      - sensor.icloud3_wazehist_track
      # 텍스트 상태들
      - sensor.jubang_siggiseceoggi_current_status
      - sensor.jubang_siggiseceoggi_current_cycle
      - binary_sensor.jubang_gimcinaengjanggo_fresh_air_filter
      - sensor.*_reachable
      - sensor.*_status_text
      - sensor.*_state_text
      - sensor.*_description
      - sensor.*mode_text
      - sensor.*condition

  # === 태그/속성 설정 ===
  tags_attributes:
    - friendly_name
    - device_class
    - unit_of_measurement
    - area_id
    - state_class
  ignore_attributes:
    - attribution
    - icon
    - entity_picture
    - suggested_display_precision
    - suggested_precision
    - restore_state
    - supported_features
    - source_type
    - available_modes
    - hvac_modes
    - preset_modes
    - context_id
    - context_user_id
    - context_parent_id
    - last_changed
    - last_updated
    - assumed_state

# ===========================
# Lovelace 설정
# ===========================
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/multiple-entity-row/multiple-entity-row.js
      type: module
    - url: /hacsfiles/config-template-card/config-template-card.js
      type: module
    - url: /hacsfiles/lovelace-horizon-card/lovelace-horizon-card.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/mushroom/mushroom.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
    # 추가 커스텀 카드들
    - url: /hacsfiles/apexcharts-card/apexcharts-card.js
      type: module
    - url: /hacsfiles/battery-state-card/battery-state-card.js
      type: module