# 디폴트 환경 설정
default_config:

# 프론트엔드 테마 설정
frontend:
  extra_module_url:
    - /hacsfiles/Bubble-Card/bubble-pop-up-fix.js
  themes: !include_dir_merge_named themes

#
scene: !include_dir_merge_list scenes
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
template: !include templates.yaml
influxdb: !include influxdb.yaml
group: !include groups.yaml

command_line:
  - sensor:
      name: Pi5 Fan Speed
      unique_id: pi5_fan_rpm
      scan_interval: 15
      command: "cat /sys/devices/platform/cooling_fan/hwmon/*/fan1_input"
      unit_of_measurement: "RPM"
      value_template: "{{ value }}"

# Enable Pyscript custom integration for image pipeline
pyscript:

# SSO 환경 설정
# 1. Reverse Proxy 설정
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24 # Supervisor 애드온 네트워크
    - 192.168.0.0/24 # NPM이 속한 내부 네트워크 대역
    - 127.0.0.1 # 로컬 루프백

  # ssl 설정
  # server_port: 443
  # ssl_certificate: /ssl/fullchain.pem
  # ssl_key: /ssl/privkey.pem

# 2. oicd 설정
# openid:
#   client_id: "<AUTHENTIK_CLIENT_ID>"
#   client_secret: "<AUTHENTIK_CLIENT_SECRET>"
#   configure_url: "https://auth.example.com/application/o/<provider-slug>/.well-known/openid-configuration"
#   username_field: "preferred_username"   # Authentik에서 이 클레임이 나오게 매핑했을 것
#   scope: "openid profile email"
#   block_login: false
#   openid_text: "Login with Authentik (OIDC)"
# (IdP가 Authorization 헤더를 싫어하면)
# use_auth_header: false

# 재연결 및 타임아웃 설정
recorder:
  commit_interval: 5
  purge_keep_days: 7

# Lovelace 설정
lovelace:
  mode: storage
  resources:
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/Bubble-Card/bubble-card.js
      type: module
    - url: /hacsfiles/Bubble-Card/bubble-pop-up-fix.js
      type: module
    - url: /hacsfiles/lovelace-mushroom/mushroom.js
      type: module
  dashboards:
    ui-minimalist:
      mode: yaml
      filename: ui_lovelace_minimalist/dashboard/ui-lovelace.yaml
      title: UI Lovelace Minimalist
      icon: mdi:flower
      show_in_sidebar: true
    mobile-dashboard:
      mode: yaml
      filename: ui_lovelace_minimalist/dashboard/mobile-dashboard.yaml
      title: CareDian Mobile
      icon: mdi:cellphone
      show_in_sidebar: true
    caredian-popup:
      mode: yaml
      filename: ui_lovelace_minimalist/dashboard/caredian-popup.yaml
      title: CareDian Pop-up
      icon: mdi:gesture-tap
      show_in_sidebar: true
    bubble-dashboard:
      mode: yaml
      filename: lovelace/views/bubble-dashboard.yaml
      title: Bubble
      icon: mdi:circle
      show_in_sidebar: true

# Gas meter (ESP32-CAM + OCR)   #
homeassistant:
  media_dirs:
    local: /config/www
    gas: /config/www/tmp/gas

input_number:
  gas_meter_2:
    name: box
    min: 0
    max: 99999
    step: 0.001
    unit_of_measurement: m³

input_text:
  gas_message_2:
    name: gas message 2
    max: 255

utility_meter:
  gas_meter_monthly:
    source: input_number.gas_meter_2
    cycle: monthly
# HA -> FastAPI Webhook
# rest_command: !include webhook.yaml
