# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include_dir_merge_list scenes
sensor: !include sensors.yaml
template: !include templates.yaml
influxdb: !include influxdb.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
    - 172.30.0.0/16

# 재연결 및 타임아웃 설정
recorder:
  commit_interval: 5
  purge_keep_days: 7

# ===========================
# Lovelace 설정
# ===========================
# YAML 편집 모드 해제 (UI 편집 모드 사용)
lovelace:
  mode: storage
  resources:
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/apexcharts-card/apexcharts-card.js
      type: module
    - url: /hacsfiles/stack-in-card/stack-in-card.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
  dashboards:
    ulm_minimalist:
      mode: yaml
      title: "ULM"
      icon: mdi:home
      show_in_sidebar: true
      filename: ui_lovelace_minimalist/dashboard/ui-lovelace.yaml

# 로거 설정 이동(센서 파일에서 분리)
logger:
  default: warning
  logs:
    homeassistant.components.xbox: critical
    homeassistant.components.xbox.coordinator: critical
    homeassistant.components.rpi_power: error
    custom_components.smartthinq_sensors: debug
    custom_components.ble_monitor: info
    # SmartThings Customize 디버깅
    custom_components.smartthings_customize: debug
    custom_components.smartthings_customize.common: debug
    custom_components.smartthings_customize.config_flow: debug
    # 인증 관련 로그 조정
    homeassistant.components.http.ban: warning
    homeassistant.components.websocket_api: warning
    # Bestin 컴포넌트 모니터링
    custom_components.bestin: info
