# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include_dir_merge_list scenes
sensor: !include sensors.yaml
template: !include templates.yaml
influxdb: !include influxdb.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
    - 172.30.0.0/16
  ip_ban_enabled: false

# ===========================
# Lovelace 설정
# ===========================
# YAML 편집 모드 해제 (UI 편집 모드 사용)
# lovelace:
#   mode: yaml
#   resources:
#     - url: /hacsfiles/button-card/button-card.js
#       type: module
#     - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
#       type: module
#     - url: /hacsfiles/multiple-entity-row/multiple-entity-row.js
#       type: module
#     - url: /hacsfiles/config-template-card/config-template-card.js
#       type: module
#     - url: /hacsfiles/lovelace-horizon-card/lovelace-horizon-card.js
#       type: module
#     - url: /hacsfiles/lovelace-layout-card/layout-card.js
#       type: module
#     - url: /hacsfiles/lovelace-card-mod/card-mod.js
#       type: module
#     - url: /hacsfiles/mushroom/mushroom.js
#       type: module
#     - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
#       type: module
#     - url: /hacsfiles/Bubble-Card/bubble-card.js
#       type: module
#     - url: /hacsfiles/apexcharts-card/apexcharts-card.js
#       type: module
#     - url: /hacsfiles/battery-state-card/battery-state-card.js
#       type: module

# 로거 설정 이동(센서 파일에서 분리)
logger:
  default: info
  logs:
    homeassistant.components.xbox: critical
    homeassistant.components.xbox.coordinator: critical
    homeassistant.components.rpi_power: error
    custom_components.smartthinq_sensors: debug
    custom_components.ble_monitor: info
