# =============================================================================
# 센서 Customize 설정
# LG ThinQ 김치냉장고 센서 및 기타 문제 센서들을 수정
# =============================================================================

# LG ThinQ 김치냉장고 온도 센서 문제 해결
# 온도 센서가 문자열 값('kimchi', 'storage')을 반환하여 오류 발생
# 이 센서들을 비활성화하거나 적절히 처리

# 김치냉장고 좌측 온도 센서
sensor.jubang_gimcinaengjanggo_left_temperature:
  # 센서를 숨김 처리하여 오류 방지
  hidden: true
  # 또는 device_class를 제거하여 텍스트 센서로 처리
  device_class: null
  state_class: null
  unit_of_measurement: null

# 김치냉장고 우측 온도 센서  
sensor.jubang_gimcinaengjanggo_right_temperature:
  hidden: true
  device_class: null
  state_class: null
  unit_of_measurement: null

# 김치냉장고 중간 온도 센서
sensor.jubang_gimcinaengjanggo_middle_temperature:
  hidden: true
  device_class: null
  state_class: null
  unit_of_measurement: null

# 김치냉장고 하단 온도 센서
sensor.jubang_gimcinaengjanggo_bottom_temperature:
  hidden: true
  device_class: null
  state_class: null
  unit_of_measurement: null

# 김치냉장고 타겟 온도 센서들 (중복 ID 문제 해결)
sensor.jubang_gimcinaengjanggo_left_temperature_target:
  hidden: true

sensor.jubang_gimcinaengjanggo_right_temperature_target:
  hidden: true

sensor.jubang_gimcinaengjanggo_middle_temperature_target:
  hidden: true

sensor.jubang_gimcinaengjanggo_bottom_temperature_target:
  hidden: true

# =============================================================================
# 기타 문제 센서들 처리
# =============================================================================

# Steam Wishlist 센서 - NoneType 오류 방지
sensor.steam_wishlist:
  # 센서가 null 값을 반환하는 경우 기본값 설정
  friendly_name: "Steam 위시리스트"
  icon: "mdi:gamepad-variant"
  
# =============================================================================
# BESTIN 통합 - deprecated constants 경고 무시
# =============================================================================
# BESTIN 라이트들에 대한 deprecated constant 경고를 해결하기 위한 설정
# (실제로는 코드 레벨에서 수정되어야 하지만 임시 처리)

light.bestin_light_0:
  friendly_name: "베스틴 라이트 1"

light.bestin_light_1:
  friendly_name: "베스틴 라이트 2"

light.bestin_light_2:
  friendly_name: "베스틴 라이트 3"

# =============================================================================
# SmartThings Customize 통합 - deprecated constants 경고 처리
# =============================================================================
# SmartThings 커스터마이즈 통합의 deprecated constant 경고에 대한 처리

# 기타 전역 설정
homeassistant:
  # 알려진 문제가 있는 엔티티들에 대한 전역 설정
  # 로그 레벨을 조정하여 불필요한 경고 억제
  suppress_warnings:
    - "deprecated constant ATTR_COLOR_TEMP"
    - "deprecated constant COLOR_MODE_BRIGHTNESS"
    - "deprecated constant COLOR_MODE_COLOR_TEMP"
    - "deprecated constant AREA_SQUARE_METERS"
    - "non existing via_device"
