## switch → light 매핑 (조명/등 전용)
- platform: switch
  name: geosil_jomyeong_1beon
  entity_id: switch.geosil_jomyeong_1beon
- platform: switch
  name: geosil_jomyeong_2beon
  entity_id: switch.geosil_jomyeong_2beon
- platform: switch
  name: geosil_jomyeong_3beon
  entity_id: switch.geosil_jomyeong_3beon
- platform: switch
  name: sihas_switch_1
  entity_id: switch.sihas_switch_1
- platform: switch
  name: sihas_switch_2
  entity_id: switch.sihas_switch_2
- platform: switch
  name: sihas_switch_3
  entity_id: switch.sihas_switch_3
- platform: switch
  name: sihas_switch_4
  entity_id: switch.sihas_switch_4
- platform: switch
  name: sihas_switch_5
  entity_id: switch.sihas_switch_5
- platform: switch
  name: deureseurum_deung
  entity_id: switch.deureseurum_deung
- platform: switch
  name: hwajangdae_deung
  entity_id: switch.hwajangdae_deung
- platform: switch
  name: anbang_hwajangsil_deung
  entity_id: switch.anbang_hwajangsil_deung
- platform: switch
  name: anbang_syaweosil_deung
  entity_id: switch.anbang_syaweosil_deung

