# ===========================
# 추가 센서 통합
# ===========================

# 시간 및 날짜
- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"
    - "date_time_utc"
    - "date_time_iso"
    - "time_date"
    - "time_utc"
