title: CareDian 스마트홈 대시보드
views:
  - title: 홈
    path: home
    # rounded/ui 레이아웃: 그리드 기반의 여백/둥근 모서리 디자인
    type: custom:grid-layout
    layout:
      grid-template-columns: repeat(auto-fit, minmax(320px, 1fr))
      grid-template-rows: auto
      grid-gap: 12px
      margin: 12px
      mediaquery:
        "(max-width: 600px)":
          grid-template-columns: 1fr
          margin: 6px
        "(min-width: 1200px)":
          grid-template-columns: repeat(3, 1fr)
    
    cards:
      # ======================
      # 상단: 시간/날씨/집 상태 개요
      # - 총 4개의 배지형 버튼으로 현재 온도/습도/총 전력/재실 표시
      # - rounded/ui 스타일을 카드 모서리 둥글게 적용
      # ======================
      - type: vertical-stack
        view_layout:
          grid-column: 1 / -1
        card_mod:
          style: |
            ha-card {
              background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
              color: white;
              border-radius: 16px;
              box-shadow: 0 4px 20px rgba(0,0,0,0.2);
              margin-bottom: 8px;
            }
        cards:
          - type: horizontal-stack
            cards:
              # 현재 시간 (rounded 배지)
              - type: custom:button-card
                entity: sensor.time
                name: 현재 시간
                icon: mdi:clock-outline
                show_state: true
                show_name: true
                styles:
                  card:
                    - background: black
                    - color: white
                    - border-radius: 999px
                    - padding: 8px 12px
                  name:
                    - color: white
                    - font-size: 14px
                  state:
                    - color: white
                    - font-size: 18px
                    - font-weight: bold

              # 날씨 요약 온도 배지 (weather 엔티티 대신 현재 온도 센서 표시)
              - type: custom:button-card
                entity: sensor.seutaendeuhyeong_eeokeon_temperature
                name: 실내 온도
                icon: mdi:thermometer
                show_state: true
                show_name: true
                styles:
                  card:
                    - background: black
                    - color: white
                    - border-radius: 999px
                    - padding: 8px 12px
                  name:
                    - color: white
                    - font-size: 14px
                  state:
                    - color: white
                    - font-size: 18px
                    - font-weight: bold
              # 실내 습도 배지
              - type: custom:button-card
                entity: sensor.seutaendeuhyeong_eeokeon_humidity
                name: 실내 습도
                icon: mdi:water-percent
                show_state: true
                show_name: true
                styles:
                  card:
                    - background: black
                    - color: white
                    - border-radius: 999px
                    - padding: 8px 12px
                  name:
                    - color: white
                    - font-size: 14px
                  state:
                    - color: white
                    - font-size: 18px
                    - font-weight: bold
                  icon:
                    - color: white
                    - width: 24px
                    - height: 24px

              # 총 전력 소비 배지 (템플릿 센서 사용)
              - type: custom:button-card
                entity: sensor.total_power_consumption
                name: 총 전력
                icon: mdi:lightning-bolt-circle
                show_state: true
                show_name: true
                styles:
                  card:
                    - background: black
                    - color: white
                    - border-radius: 999px
                    - padding: 8px 12px
                  name:
                    - color: white
                    - font-size: 14px
                  state:
                    - color: white
                    - font-size: 18px
                    - font-weight: bold
                  icon:
                    - color: white
                    - width: 24px
                    - height: 24px

              # 집 상태 배지 (재실 템플릿)
              - type: custom:button-card
                entity: binary_sensor.someone_home
                name: 집 상태
                show_state: true
                show_name: true
                state_display: |
                  [[[
                    return entity.state === 'on' ? '재실' : '부재';
                  ]]]
                styles:
                  card:
                    - background: black
                    - color: white
                    - border-radius: 999px
                    - padding: 8px 12px
                  name:
                    - color: white
                    - font-size: 14px
                  state:
                    - color: white
                    - font-size: 18px
                    - font-weight: bold
                  icon:
                    - color: white
                    - width: 24px
                    - height: 24px
                icon: |
                  [[[
                    return entity.state === 'on' ? 'mdi:home-account' : 'mdi:home-outline';
                  ]]]

      # ======================
      # 중앙: 환경 센서(기후 제어 포함)
      # ======================
      - type: thermostat
        entity: climate.seutaendeuhyeong_eeokeon
        title: 🌡️ 스탠드형 에어컨
        card_mod:
          style: |
            ha-card {
              border-radius: 12px;
              box-shadow: 0 2px 12px rgba(0,0,0,0.15);
            }

      # ======================
      # 하단: 조명 & 전력 제어
      # ======================
      - type: vertical-stack
        title: 💡 조명 & 전력
        card_mod:
          style: |
            ha-card {
              border-radius: 12px;
              box-shadow: 0 2px 12px rgba(0,0,0,0.15);
            }
        cards:
          # 조명 제어
          - type: entities
            title: 조명 제어
            show_header_toggle: true
            state_color: true
            entities:
              - entity: light.zigbee_dimmer
                name: 주방 조명
                icon: mdi:lightbulb
              - entity: light.smart_bulb
                name: 스마트 전구
                icon: mdi:lightbulb-outline
              - entity: light.deseukeutab_jeonweon
                name: 데스크톱 전원
                icon: mdi:desktop-classic

          # 전력 모니터링
          - type: entities
            title: 실시간 전력
            entities:
              - entity: sensor.total_power_consumption
                name: 총 전력 소비
                icon: mdi:lightning-bolt-circle
              - entity: sensor.seutaendeuhyeong_eeokeon_power
                name: 에어컨
                icon: mdi:air-conditioner
              - entity: sensor.zigbee_dimmer_power
                name: 주방 조명
                icon: mdi:lightbulb
              - entity: sensor.deseukeutab_jeonweon_power
                name: 데스크톱
                icon: mdi:desktop-classic

          # 전력 사용량 그래프
          - type: custom:mini-graph-card
            entities:
              - entity: sensor.total_power_consumption
                name: 총합
                color: '#e67e22'
              - entity: sensor.seutaendeuhyeong_eeokeon_power
                name: 에어컨
                color: '#3498db'
            hours_to_show: 12
            points_per_hour: 2
            name: 전력 소비 추이 (12시간)
            show:
              fill: fade

      # ======================
      # 하단 스크롤 섹션: 주방 가전 상세
      # ======================
      - type: vertical-stack
        title: 🍽️ 주방 가전
        card_mod:
          style: |
            ha-card {
              border-radius: 12px;
              box-shadow: 0 2px 12px rgba(0,0,0,0.15);
            }
        cards:
          # 식기세척기 상태
          - type: entities
            title: 식기세척기
            entities:
              - entity: binary_sensor.jubang_siggiseceoggi_door
                name: 문 상태
                icon: mdi:door
              - entity: sensor.jubang_siggiseceoggi_remaining_time
                name: 남은 시간
                icon: mdi:timer-outline
              - entity: binary_sensor.jubang_siggiseceoggi_rinse_refill_needed
                name: 린스 보충 필요
                icon: mdi:bottle-tonic-outline
              - entity: sensor.jubang_siggiseceoggi_rinse_aid_dispenser_level
                name: 린스 잔여량
                icon: mdi:cup-water

          # 김치냉장고 온도
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                entity: sensor.kimchi_fridge_avg_temperature
                name: 평균 온도
                icon: mdi:thermometer
                show_state: true
                show_name: true
                styles:
                  card:
                    - border-radius: 8px
                  name:
                    - font-size: 12px
                  state:
                    - font-size: 18px
                    - font-weight: bold

              - type: entities
                entities:
                  - entity: sensor.jubang_gimcinaengjanggo_left_temperature
                    name: 좌측
                    icon: mdi:thermometer-low
                  - entity: sensor.jubang_gimcinaengjanggo_right_temperature
                    name: 우측
                    icon: mdi:thermometer-high

      # ======================
      # 하단 스크롤 섹션: 헬스 & 웨어러블
      # ======================
      - type: vertical-stack
        title: 💪 헬스 & 웨어러블
        card_mod:
          style: |
            ha-card {
              border-radius: 12px;
              box-shadow: 0 2px 12px rgba(0,0,0,0.15);
            }
        cards:
          # BLE 웨어러블
          - type: entities
            title: BLE 웨어러블
            entities:
              - entity: sensor.ble_heart_rate_e0e33e6221b5
                name: 심박수
                icon: mdi:heart-pulse
              - entity: sensor.ble_steps_e0e33e6221b5
                name: 걸음수
                icon: mdi:walk

          # 구강 건강
          - type: entities
            title: 구강 건강 모니터링
            entities:
              - entity: binary_sensor.ble_toothbrush_f45eab216f50
                name: 전동칫솔 상태
                icon: mdi:toothbrush-electric
              - entity: sensor.smart_series_7000_6f50_duration
                name: 양치 시간
                icon: mdi:timer
              - entity: sensor.smart_series_7000_6f50_pressure
                name: 칫솔 압력
                icon: mdi:gauge

      # ======================
      # 배터리 상태(요약 + 상세)
      # ======================
      - type: vertical-stack
        title: 🔋 배터리 관리
        card_mod:
          style: |
            ha-card {
              border-radius: 12px;
              box-shadow: 0 2px 12px rgba(0,0,0,0.15);
            }
        cards:
          # 배터리 요약
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                entity: sensor.average_device_battery
                name: 평균 배터리
                icon: mdi:battery
                show_state: true
                show_name: true
                styles:
                  card:
                    - border-radius: 8px
                  name:
                    - font-size: 12px
                  state:
                    - font-size: 18px
                    - font-weight: bold

              - type: custom:button-card
                entity: binary_sensor.low_battery_devices
                name: 저배터리 알림
                show_state: true
                show_name: true
                state_display: |
                  [[[
                    return entity.state === 'on' ? '주의!' : '정상';
                  ]]]
                styles:
                  card:
                    - border-radius: 8px
                    - background: |
                        [[[
                          return entity.state === 'on' ? '#e74c3c' : '#2ecc71';
                        ]]]
                    - color: white
                  name:
                    - font-size: 12px
                    - color: white
                  state:
                    - font-size: 14px
                    - font-weight: bold
                    - color: white

          # 개별 배터리 상태
          - type: entities
            title: 개별 배터리 상태
            entities:
              - entity: sensor.gimuhyeonyi_apple_watch_battery
                name: Apple Watch
                icon: mdi:watch
              - entity: sensor.gimuhyeonyi_macbook_pro_battery
                name: MacBook Pro
                icon: mdi:laptop
              - entity: sensor.uhyeonyi_ipad_pro_battery
                name: iPad Pro
                icon: mdi:tablet
              - entity: sensor.uhyeonyi_iphone_xs_battery
                name: iPhone XS
                icon: mdi:cellphone

      # ======================
      # 네트워크 & 시간 정보
      # ======================
      - type: vertical-stack
        title: 🌐 네트워크 & 시간
        card_mod:
          style: |
            ha-card {
              border-radius: 12px;
              box-shadow: 0 2px 12px rgba(0,0,0,0.15);
            }
        cards:
          # 네트워크 상태
          - type: entities
            title: 네트워크 연결
            entities:
              - entity: sensor.192_168_1_1_devices_connected
                name: 연결된 기기
                icon: mdi:devices
              - entity: sensor.fast_com_download
                name: 인터넷 속도
                icon: mdi:speedometer
              - entity: sensor.paul_router_download_speed
                name: 다운로드
                icon: mdi:download
              - entity: sensor.paul_router_upload_speed
                name: 업로드
                icon: mdi:upload

          # 네트워크 속도 그래프
          - type: custom:mini-graph-card
            entities:
              - entity: sensor.fast_com_download
                name: 다운로드
                color: '#03A9F4'
              - entity: sensor.paul_router_upload_speed
                name: 업로드
                color: '#FF9800'
            hours_to_show: 12
            points_per_hour: 2
            name: 네트워크 속도 (12시간)
            show:
              fill: fade

      # ======================
      # 존재감지 & 상태
      # ======================
      - type: entities
        title: 🏠 스마트홈 상태
        state_color: true
        card_mod:
          style: |
            ha-card {
              border-radius: 12px;
              box-shadow: 0 2px 12px rgba(0,0,0,0.15);
            }
        entities:
          - entity: binary_sensor.someone_home
            name: 집에 사람 있음
            icon: mdi:home-account
          - entity: binary_sensor.iphone_presence
            name: iPhone 감지
            icon: mdi:cellphone-check
          - entity: binary_sensor.workday_sensor
            name: 오늘 근무일
            icon: mdi:briefcase
          - entity: binary_sensor.low_battery_devices
            name: 저배터리 주의
            icon: mdi:battery-alert

  # ======================
  # 에너지 탭 (NEW)
  # ======================
  - title: 에너지
    path: energy
    icon: mdi:lightning-bolt
    cards:
      # 에너지 소비 요약
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            entity: sensor.total_power_consumption
            name: 현재 총 전력
            show_state: true
            show_name: true
            styles:
              card:
                - background: linear-gradient(45deg, #FF6B6B, #4ECDC4)
                - color: white
                - border-radius: 12px
              name:
                - color: white
                - font-size: 16px
              state:
                - color: white
                - font-size: 32px
                - font-weight: bold

      # 실시간 전력 소비
      - type: entities
        title: 실시간 전력 소비
        entities:
          - entity: sensor.seutaendeuhyeong_eeokeon_power
            name: 에어컨 전력
            icon: mdi:air-conditioner
          - entity: sensor.zigbee_dimmer_power
            name: 주방 조명
            icon: mdi:lightbulb
          - entity: sensor.deseukeutab_jeonweon_power
            name: 데스크톱
            icon: mdi:desktop-classic

      # 누적 에너지 소비
      - type: entities
        title: 누적 에너지 소비량
        entities:
          - entity: sensor.seutaendeuhyeong_eeokeon_energy
            name: 에어컨 총 에너지
            icon: mdi:air-conditioner
          - entity: sensor.zigbee_dimmer_energy
            name: 주방 조명 총 에너지
            icon: mdi:lightbulb
          - entity: sensor.deseukeutab_jeonweon_energy
            name: 데스크톱 총 에너지
            icon: mdi:desktop-classic

  # ======================
  # 시스템 탭 (NEW)
  # ======================
  - title: 시스템
    path: system
    icon: mdi:cog
    cards:
      # 시스템 리소스
      - type: entities
        title: 시스템 리소스
        entities:
          - entity: sensor.processor_use
            name: CPU 사용률
            icon: mdi:cpu-64-bit
          - entity: sensor.memory_use_percent
            name: 메모리 사용률
            icon: mdi:memory
          - entity: sensor.disk_use_percent
            name: 디스크 사용률
            icon: mdi:harddisk
          - entity: sensor.load_1m
            name: 시스템 로드
            icon: mdi:gauge

      # 네트워크 정보
      - type: entities
        title: 네트워크 정보
        entities:
          - entity: sensor.network_in_eth0
            name: 네트워크 수신
            icon: mdi:download
          - entity: sensor.network_out_eth0
            name: 네트워크 송신
            icon: mdi:upload
          - entity: sensor.last_boot
            name: 마지막 부팅
            icon: mdi:restart

      # 시간 정보
      - type: entities
        title: 시간 & 환경
        entities:
          - entity: sensor.time
            name: 현재 시간
            icon: mdi:clock-outline
          - entity: sensor.date
            name: 오늘 날짜
            icon: mdi:calendar
          # season 통합 제거에 따라 카드에서 제외
          - entity: sun.sun
            name: 태양
            icon: mdi:weather-sunny