---
button_card_templates: !include_dir_merge_named "ui_lovelace_minimalist/ulm_templates/"

title: "UI Lovelace Minimalist"
theme: "minimalist-desktop"
background: "var(--background-image)"
views:
  - title: "Home"
    path: home
    icon: "mdi:home"
    cards:
      - type: "vertical-stack"
        cards:
          - type: "custom:button-card"
            template: "card_title"
            name: "홈 요약"
            label: "전력 · 환경 · 조명 · 미디어"
          - type: "grid"
            columns: 3
            square: false
            cards:
              - type: "custom:button-card"
                template: "card_generic"
                entity: sensor.total_power_consumption
                name: "현재 전력"
              - type: "custom:button-card"
                template: "card_generic"
                entity: sensor.seutaendeuhyeong_eeokeon_energy
                name: "이번 달 요금"
              - type: "custom:button-card"
                template: "card_generic"
                entity: sensor.unavailable_entities_count
                name: "문제 엔티티"
          - type: "custom:apexcharts-card"
            hours_12: false
            header:
              show: false
            graph_span: 12h
            series:
              - entity: sensor.total_power_consumption
                name: "총 전력(W)"
                type: area
                group_by:
                  func: avg
                  duration: 10m
              - entity: sensor.seutaendeuhyeong_eeokeon_power
                name: "에어컨 전력(W)"
                type: line
                group_by:
                  func: avg
                  duration: 10m
              - entity: sensor.seutaendeuhyeong_eeokeon_energy
                name: "에어컨 에너지(kWh)"
                type: line
                yaxis_id: kwh
                group_by:
                  func: last
                  duration: 1d
            yaxis:
              - id: "power"
                show: true
              - id: "kwh"
                opposite: true
                show: true
          - type: "custom:button-card"
            template: "card_title"
            name: "환경"
          - type: "grid"
            columns: 2
            square: false
            cards:
              - type: "custom:button-card"
                template: "card_temperature"
                entity: sensor.seutaendeuhyeong_eeokeon_temperature
                name: "실내 온도"
              - type: "custom:button-card"
                template: "card_temperature"
                entity: sensor.seutaendeuhyeong_eeokeon_humidity
                name: "실내 습도"
              - type: "custom:button-card"
                template: "card_temperature"
                entity: sensor.kimchi_fridge_avg_temperature
                name: "김치냉장고 평균"
              - type: "custom:button-card"
                template: "card_climate"
                entity: climate.seutaendeuhyeong_eeokeon
                name: "에어컨"
          - type: "custom:button-card"
            template: "card_title"
            name: "조명"
          - type: "grid"
            columns: 2
            square: false
            cards:
              - type: "custom:button-card"
                template: "card_light"
                entity: light.smart_bulb
                name: "책상 조명"
                variables:
                  ulm_card_light_enable_slider: true
                  ulm_card_light_enable_color: true
              - type: "custom:button-card"
                template: "card_light"
                entity: light.smart_bulb_2
                name: "스마트전구2"
                variables:
                  ulm_card_light_enable_slider: true
              - type: "custom:button-card"
                template: "card_light"
                entity: light.smart_bulb_3
                name: "스마트전구3"
              - type: "custom:button-card"
                template: "card_light"
                entity: light.rt_ac68u_led
                name: "라우터 LED"
              # 제거: 존재하지 않는 엔티티
              # - type: "custom:button-card"
              #   template: "card_light"
              #   entity: light.hagyeong_floor
              #   name: "하경 플로어"
          - type: "custom:button-card"
            template: "card_title"
            name: "미디어"
          - type: "grid"
            columns: 3
            square: false
            cards:
              - type: "custom:button-card"
                template: "card_media_player"
                entity: media_player.uhyeonibang
                name: "우현이방"
              - type: "custom:button-card"
                template: "card_media_player"
                entity: media_player.spotify_gimuhyeon
                name: "Spotify"
              - type: "custom:button-card"
                template: "card_media_player"
                entity: media_player.vlc_telnet
                name: "VLC"
          - type: "custom:button-card"
            template: "card_title"
            name: "진단/배터리"
          - type: "grid"
            columns: 3
            square: false
            cards:
              - type: "custom:button-card"
                template: "card_binary_sensor_alert"
                entity: binary_sensor.low_battery_devices
                name: "저배터리"
                variables:
                  ulm_card_binary_sensor_alert: true
              - type: "custom:button-card"
                template: "card_battery"
                entity: sensor.gimuhyeonyi_apple_watch_battery
                name: "Watch"
                variables:
                  ulm_card_battery_battery_state_entity_id: sensor.gimuhyeonyi_apple_watch_battery
                  ulm_card_battery_battery_level_danger: 20
                  ulm_card_battery_battery_level_warning: 50
              - type: "custom:button-card"
                template: "card_battery"
                entity: sensor.gimuhyeonyi_macbook_pro_battery
                name: "MacBook"
                variables:
                  ulm_card_battery_battery_state_entity_id: sensor.gimuhyeonyi_macbook_pro_battery
              - type: "custom:button-card"
                template: "card_battery"
                entity: sensor.uhyeonyi_ipad_pro_battery
                name: "iPad"
                variables:
                  ulm_card_battery_battery_state_entity_id: sensor.uhyeonyi_ipad_pro_battery
              - type: "custom:button-card"
                template: "card_battery"
                entity: sensor.uhyeonyi_iphone_xs_battery
                name: "iPhone"
                variables:
                  ulm_card_battery_battery_state_entity_id: sensor.uhyeonyi_iphone_xs_battery
