esphome:
  name: korvo2-v31
  friendly_name: korvo2 v3.1

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "BB1TSmyaCERwNZKiciPyJ3dix31xo/YG4x5tUS6iwnI="

ota:
  - platform: esphome
    password: "7171fe5355009bcb38389b32fc21b963"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Korvo2-V31 Fallback Hotspot"
    password: "2O55UcQ8fslW"

captive_portal:
    