alias: 예시 자동화 - 홈 모드 토글시 알림
mode: single
trigger:
  - platform: state
    entity_id: input_boolean.trigger_home_absence
condition: []
action:
  - service: persistent_notification.create
    data:
      title: 홈 상태 변경
      message: "부재/재실 토글 상태가 변경되었습니다."
