esphome:
  name: korvo-gas-cam

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
  flash_size: 16MB

psram:
  mode: octal
  speed: 80MHz   # S3 N16R8 계열 권장 값

logger:
api:
ota:
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd

i2c:
  id: camera_i2c
  sda: GPIO17
  scl: GPIO18
  scan: false

# OV2640 핀 매핑(Korvo-2 v3.1)
esp32_camera:
  name: "Gas Meter Cam"
  i2c_id: camera_i2c
  external_clock:
    pin: GPIO40       # XCLK
    frequency: 20MHz
  data_pins: [GPIO13, GPIO47, GPIO14, GPIO3, GPIO12, GPIO42, GPIO41, GPIO39]   # D2..D9
  vsync_pin: GPIO21
  href_pin:  GPIO38
  pixel_clock_pin: GPIO11
  resolution: 1024x768
  jpeg_quality: 10
  max_framerate: 10 fps
  idle_framerate: 0.2 fps

# 선택: 웹 스트림(MJPEG)도 열기
esp32_camera_web_server:
  - port: 8080   # mjpeg
  - port: 8081   # snapshot