esphome:
  name: korvo2-v31
  friendly_name: korvo2 v3.1

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "E/yIqQR/B07Y6AoD0dae/ScMluQLJMN+ZNdZY6u186Q="

ota:
  - platform: esphome
    password: "e662be58f4c3439b34ff066b7ac518c9"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Korvo2-V31 Fallback Hotspot"
    password: "CgFotoQWumuQ"

captive_portal:
    