esphome:
  name: korvo2-v31
  friendly_name: korvo2 v3.1

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "j/WzM/a7Tfa87W9KXF/JaF5XHJ/yZZWrP76057oNFCo="

ota:
  - platform: esphome
    password: "2cf7a586552778fa1a96fdc6c0fb0ec3"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Korvo2-V31 Fallback Hotspot"
    password: "YzyoZg77BGSr"

captive_portal:
    